spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blocklang
    username: postgres
    password: abc123
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6979d9b09aece54ff960
            client-secret: 9892875165b26db23601e59e75fddcca4ce36514
server:
  tomcat:
    uri-encoding: UTF-8
    compression: on
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpg,image/png,image/gif
# security:
#   oauth2:
#     client:
#       # 测试专用
#       clientId: 6979d9b09aece54ff960
#       clientSecret: 9892875165b26db23601e59e75fddcca4ce36514
#       accessTokenUri: https://github.com/login/oauth/access_token
#       userAuthorizationUri: https://github.com/login/oauth/authorize
#       clientAuthenticationScheme: form
#     resource:
#       userInfoUri: https://api.github.com/user