spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgm-2ze9a80ozt4i63ea14790.pg.rds.aliyuncs.com:3433/blocklang
    username: blocklang
    password: blocklang%46
    # url: jdbc:postgresql://127.0.0.1:5432/blocklang
    # username: postgres
    # password: abc123
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6979d9b09aece54ff960
            client-secret: 9892875165b26db23601e59e75fddcca4ce36514
          qq:
            provider: qq
            client-id: 101558855
            client-secret: 920e1db9e7cd295dbd1da85b6a3a23cf
            authorizationGrantType: authorization_code
            redirectUriTemplate: https://blocklang.com/login/oauth2/code/qq
            scope: get_user_info
        provider:
          qq:
            authorization-uri: https://graph.qq.com/oauth2.0/authorize
            token-uri: https://graph.qq.com/oauth2.0/token
            user-info-uri: https://graph.qq.com/user/get_user_info
            user-name-attribute: openid
            jwk-set-uri: https://graph.qq.com/oauth2.0/token
  jackson:
    default-property-inclusion: non_null
server:
  tomcat:
    uri-encoding: UTF-8
    compression: on
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpg,image/png,image/gif
  port: 443
  ssl:
    key-store: classpath:cert/1963553_www.blocklang.com.pfx
    key-store-password: 5CvGL3by
    keyStoreType: PKCS12
  
# security:
#   oauth2:
#     client:
#       # 测试专用
#       clientId: 6979d9b09aece54ff960
#       clientSecret: 9892875165b26db23601e59e75fddcca4ce36514
#       accessTokenUri: https://github.com/login/oauth/access_token
#       userAuthorizationUri: https://github.com/login/oauth/authorize
#       clientAuthenticationScheme: form
#     resource:
#       userInfoUri: https://api.github.com/user